// File generated by Antigravity for Aarogya Vault Patient App
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCLPmtLq6uhx226MxQNYPcBopm06lvK4A',
    appId: '1:368409267229:web:4931c4be0e24fdbd9b4af4',
    messagingSenderId: '368409267229',
    projectId: 'aarogya-vault',
    authDomain: 'aarogya-vault.firebaseapp.com',
    storageBucket: 'aarogya-vault.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCLPmtLq6uhx226MxQNYPcBopm06lvK4A',
    appId: '1:368409267229:android:4931c4be0e24fdbd9b4af4',
    messagingSenderId: '368409267229',
    projectId: 'aarogya-vault',
    storageBucket: 'aarogya-vault.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8NROFggDoapFUlAfIV1JCR_spNTenRAI',
    appId: '1:368409267229:ios:c59a1705da6f77249b4af4',
    messagingSenderId: '368409267229',
    projectId: 'aarogya-vault',
    storageBucket: 'aarogya-vault.firebasestorage.app',
    iosBundleId: 'com.aarogyavault.aarogyaVaultApp',
  );
}
