// File generated by Antigravity for Aarogya Vault Doctor App
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyForAarogyaVaultWeb',
    appId: '1:1234567890:web:aarogyavaultwebid',
    messagingSenderId: '1234567890',
    projectId: 'aarogya-vault',
    authDomain: 'aarogya-vault.firebaseapp.com',
    storageBucket: 'aarogya-vault.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyForAarogyaVaultAndroid',
    appId: '1:1234567890:android:aarogyavaultandroidid',
    messagingSenderId: '1234567890',
    projectId: 'aarogya-vault',
    storageBucket: 'aarogya-vault.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyForAarogyaVaultIos',
    appId: '1:1234567890:ios:aarogyavaultiosid',
    messagingSenderId: '1234567890',
    projectId: 'aarogya-vault',
    storageBucket: 'aarogya-vault.appspot.com',
    iosBundleId: 'com.example.doctorApp',
  );
}
