"""add_hospital_admin_entities

Revision ID: 4df1a4a05c2d
Revises: 8f42022ab545
Create Date: 2026-07-28 11:01:48.404903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4df1a4a05c2d'
down_revision: Union[str, Sequence[str], None] = '8f42022ab545'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('license_number', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hospitals_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hospitals_license_number'), ['license_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_hospitals_name'), ['name'], unique=False)

    op.create_table('pharmacy_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medicine_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('batch_number', sa.String(), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('reorder_level', sa.Integer(), nullable=False),
    sa.Column('expiry_date', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pharmacy_inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pharmacy_inventory_batch_number'), ['batch_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_pharmacy_inventory_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pharmacy_inventory_medicine_name'), ['medicine_name'], unique=False)

    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(), nullable=False),
    sa.Column('permission_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_permissions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_permissions_permission_key'), ['permission_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_permissions_role_name'), ['role_name'], unique=False)

    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('head_doctor_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['head_doctor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_departments_head_doctor_id'), ['head_doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_departments_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_departments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_departments_name'), ['name'], unique=False)

    op.create_table('emergency_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('triage_notes', sa.Text(), nullable=True),
    sa.Column('ambulance_unit', sa.String(), nullable=True),
    sa.Column('police_notified', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emergency_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emergency_cases_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_emergency_cases_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_emergency_cases_patient_id'), ['patient_id'], unique=False)

    op.create_table('hospital_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hospital_notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hospital_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_hospital_notifications_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hospital_notifications_id'), ['id'], unique=False)

    op.create_table('lab_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('test_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('results_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lab_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lab_orders_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_orders_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_orders_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_orders_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_orders_test_name'), ['test_name'], unique=False)

    op.create_table('medicine_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('medicine_name', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medicine_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medicine_requests_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medicine_requests_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medicine_requests_patient_id'), ['patient_id'], unique=False)

    op.create_table('radiology_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('modality', sa.String(), nullable=False),
    sa.Column('body_part', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('radiology_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_radiology_orders_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_radiology_orders_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_radiology_orders_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_radiology_orders_patient_id'), ['patient_id'], unique=False)

    op.create_table('department_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('total_patients', sa.Integer(), nullable=True),
    sa.Column('active_admissions', sa.Integer(), nullable=True),
    sa.Column('recorded_date', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('department_statistics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_department_statistics_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_department_statistics_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_department_statistics_recorded_date'), ['recorded_date'], unique=False)

    op.create_table('hospital_staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('role_title', sa.String(), nullable=False),
    sa.Column('shift_schedule', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hospital_staff', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hospital_staff_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hospital_staff_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hospital_staff_user_id'), ['user_id'], unique=True)

    op.create_table('medicine_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('pharmacist_id', sa.Integer(), nullable=True),
    sa.Column('issued_quantity', sa.Integer(), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pharmacist_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_id'], ['medicine_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medicine_issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medicine_issues_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medicine_issues_pharmacist_id'), ['pharmacist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medicine_issues_request_id'), ['request_id'], unique=False)

    op.create_table('wards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ward_type', sa.String(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wards_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wards_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wards_name'), ['name'], unique=False)

    op.create_table('beds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ward_id', sa.Integer(), nullable=False),
    sa.Column('bed_number', sa.String(), nullable=False),
    sa.Column('is_occupied', sa.Boolean(), nullable=False),
    sa.Column('daily_rate', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('beds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_beds_bed_number'), ['bed_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_beds_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_beds_ward_id'), ['ward_id'], unique=False)

    op.create_table('admissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('bed_id', sa.Integer(), nullable=True),
    sa.Column('admission_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('admission_date', sa.DateTime(), nullable=False),
    sa.Column('discharge_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bed_id'], ['beds.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admissions_bed_id'), ['bed_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admissions_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admissions_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admissions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admissions_patient_id'), ['patient_id'], unique=False)

    op.create_table('bed_assignment_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admission_id', sa.Integer(), nullable=False),
    sa.Column('bed_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bed_id'], ['beds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bed_assignment_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bed_assignment_history_admission_id'), ['admission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bed_assignment_history_bed_id'), ['bed_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bed_assignment_history_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bed_assignment_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bed_assignment_history_id'))
        batch_op.drop_index(batch_op.f('ix_bed_assignment_history_bed_id'))
        batch_op.drop_index(batch_op.f('ix_bed_assignment_history_admission_id'))

    op.drop_table('bed_assignment_history')
    with op.batch_alter_table('admissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admissions_patient_id'))
        batch_op.drop_index(batch_op.f('ix_admissions_id'))
        batch_op.drop_index(batch_op.f('ix_admissions_doctor_id'))
        batch_op.drop_index(batch_op.f('ix_admissions_department_id'))
        batch_op.drop_index(batch_op.f('ix_admissions_bed_id'))

    op.drop_table('admissions')
    with op.batch_alter_table('beds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_beds_ward_id'))
        batch_op.drop_index(batch_op.f('ix_beds_id'))
        batch_op.drop_index(batch_op.f('ix_beds_bed_number'))

    op.drop_table('beds')
    with op.batch_alter_table('wards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wards_name'))
        batch_op.drop_index(batch_op.f('ix_wards_id'))
        batch_op.drop_index(batch_op.f('ix_wards_department_id'))

    op.drop_table('wards')
    with op.batch_alter_table('medicine_issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicine_issues_request_id'))
        batch_op.drop_index(batch_op.f('ix_medicine_issues_pharmacist_id'))
        batch_op.drop_index(batch_op.f('ix_medicine_issues_id'))

    op.drop_table('medicine_issues')
    with op.batch_alter_table('hospital_staff', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hospital_staff_user_id'))
        batch_op.drop_index(batch_op.f('ix_hospital_staff_id'))
        batch_op.drop_index(batch_op.f('ix_hospital_staff_department_id'))

    op.drop_table('hospital_staff')
    with op.batch_alter_table('department_statistics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_department_statistics_recorded_date'))
        batch_op.drop_index(batch_op.f('ix_department_statistics_id'))
        batch_op.drop_index(batch_op.f('ix_department_statistics_department_id'))

    op.drop_table('department_statistics')
    with op.batch_alter_table('radiology_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_radiology_orders_patient_id'))
        batch_op.drop_index(batch_op.f('ix_radiology_orders_id'))
        batch_op.drop_index(batch_op.f('ix_radiology_orders_doctor_id'))
        batch_op.drop_index(batch_op.f('ix_radiology_orders_created_at'))

    op.drop_table('radiology_orders')
    with op.batch_alter_table('medicine_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicine_requests_patient_id'))
        batch_op.drop_index(batch_op.f('ix_medicine_requests_id'))
        batch_op.drop_index(batch_op.f('ix_medicine_requests_doctor_id'))

    op.drop_table('medicine_requests')
    with op.batch_alter_table('lab_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lab_orders_test_name'))
        batch_op.drop_index(batch_op.f('ix_lab_orders_patient_id'))
        batch_op.drop_index(batch_op.f('ix_lab_orders_id'))
        batch_op.drop_index(batch_op.f('ix_lab_orders_doctor_id'))
        batch_op.drop_index(batch_op.f('ix_lab_orders_created_at'))

    op.drop_table('lab_orders')
    with op.batch_alter_table('hospital_notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hospital_notifications_id'))
        batch_op.drop_index(batch_op.f('ix_hospital_notifications_hospital_id'))
        batch_op.drop_index(batch_op.f('ix_hospital_notifications_created_at'))

    op.drop_table('hospital_notifications')
    with op.batch_alter_table('emergency_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emergency_cases_patient_id'))
        batch_op.drop_index(batch_op.f('ix_emergency_cases_id'))
        batch_op.drop_index(batch_op.f('ix_emergency_cases_created_at'))

    op.drop_table('emergency_cases')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_name'))
        batch_op.drop_index(batch_op.f('ix_departments_id'))
        batch_op.drop_index(batch_op.f('ix_departments_hospital_id'))
        batch_op.drop_index(batch_op.f('ix_departments_head_doctor_id'))
        batch_op.drop_index(batch_op.f('ix_departments_code'))

    op.drop_table('departments')
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_permissions_role_name'))
        batch_op.drop_index(batch_op.f('ix_role_permissions_permission_key'))
        batch_op.drop_index(batch_op.f('ix_role_permissions_id'))

    op.drop_table('role_permissions')
    with op.batch_alter_table('pharmacy_inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pharmacy_inventory_medicine_name'))
        batch_op.drop_index(batch_op.f('ix_pharmacy_inventory_id'))
        batch_op.drop_index(batch_op.f('ix_pharmacy_inventory_batch_number'))

    op.drop_table('pharmacy_inventory')
    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hospitals_name'))
        batch_op.drop_index(batch_op.f('ix_hospitals_license_number'))
        batch_op.drop_index(batch_op.f('ix_hospitals_id'))

    op.drop_table('hospitals')
    # ### end Alembic commands ###
