"""Add doctor and role support

Revision ID: 628d8bd5d7ac
Revises: 29ac028cd5d4
Create Date: 2026-07-18 18:09:50.918973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '628d8bd5d7ac'
down_revision: Union[str, Sequence[str], None] = '29ac028cd5d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_appointments_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_foreign_key('fk_appointments_doctor', 'users', ['doctor_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_prescriptions_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_foreign_key('fk_prescriptions_doctor', 'users', ['doctor_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(), nullable=False, server_default='patient'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_prescriptions_doctor', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_prescriptions_doctor_id'))
        batch_op.drop_column('doctor_id')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_appointments_doctor', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_appointments_doctor_id'))
        batch_op.drop_column('doctor_id')

    # ### end Alembic commands ###
