"""add_firebase_uid

Revision ID: 8f42022ab545
Revises: 985b4c5b28b1
Create Date: 2026-07-22 12:34:44.669845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f42022ab545'
down_revision: Union[str, Sequence[str], None] = '985b4c5b28b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_patient_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('access_type', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('doctor_patient_access', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doctor_patient_access_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctor_patient_access_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctor_patient_access_patient_id'), ['patient_id'], unique=False)

    op.create_table('doctor_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('registration_number', sa.String(), nullable=False),
    sa.Column('specialty', sa.String(), nullable=False),
    sa.Column('hospital_name', sa.String(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('doctor_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doctor_profiles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctor_profiles_registration_number'), ['registration_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_doctor_profiles_user_id'), ['user_id'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firebase_uid', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_firebase_uid'), ['firebase_uid'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_firebase_uid'))
        batch_op.drop_column('firebase_uid')

    with op.batch_alter_table('doctor_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctor_profiles_user_id'))
        batch_op.drop_index(batch_op.f('ix_doctor_profiles_registration_number'))
        batch_op.drop_index(batch_op.f('ix_doctor_profiles_id'))

    op.drop_table('doctor_profiles')
    with op.batch_alter_table('doctor_patient_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctor_patient_access_patient_id'))
        batch_op.drop_index(batch_op.f('ix_doctor_patient_access_id'))
        batch_op.drop_index(batch_op.f('ix_doctor_patient_access_doctor_id'))

    op.drop_table('doctor_patient_access')
    # ### end Alembic commands ###
