"""add_supabase_user_id

Revision ID: 985b4c5b28b1
Revises: 628d8bd5d7ac
Create Date: 2026-07-22 10:59:30.476145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '985b4c5b28b1'
down_revision: Union[str, Sequence[str], None] = '628d8bd5d7ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supabase_user_id', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_supabase_user_id'), ['supabase_user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_supabase_user_id'))
        batch_op.drop_column('supabase_user_id')

    # ### end Alembic commands ###
